openapi: 3.1.0
tags:
  - name: signup
    description: Endpoints dealing with user signup

paths:
  /signup/details:
    post:
      tags:
        - signup
      summary: Set Profile Details (step 1/3 of signup)
      description: First step of the signup process. Validates profile details.
      operationId: signup.details
      requestBody:
        required: true
        description: Profile registration details.
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/schemas/SignupDetails"
      responses:
        "200":
          $ref: "./responses.yaml#/responses/SuccessfulSignupStep200"
        "400":
          $ref: "./errors.yaml#/components/responses/SignupDetailsValidationError"
        "409":
          $ref: "./errors.yaml#/components/responses/SignupDetailsEmailExistsError"

  /signup/password:
    post:
      tags:
        - signup
      summary: Set Password (step 2/3 of signup)
      description: |
        Allows a user to define a secure password as part of the registration flow. 
        Password must meet strength requirements.
      operationId: signup.password
      requestBody:
        required: true
        description: Password to set.
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/schemas/SignupPassword"
      responses:
        "200":
          $ref: "./responses.yaml#/responses/SuccessfulSignupStep200"
        "400":
          $ref: "./errors.yaml#/components/responses/SignupPasswordValidationError"
        "404":
          $ref: "./errors.yaml#/components/responses/SignupSessionNotFoundError"

  /signup/finalize:
    post:
      tags:
        - signup
      summary: Finalize Signup (step 3/3 of signup)
      description: |
        Final step of the signup process, creating a new user. User must accept T&C and can optionally accept marketing communications.
      operationId: signup.finalize
      requestBody:
        required: true
        description: T&C acceptance and marketing consent.
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/schemas/SignupFinalize"
      responses:
        "201":
          description: "Created"
        "400":
          $ref: "./errors.yaml#/components/responses/SignupTermsValidationError"
        "404":
          $ref: "./errors.yaml#/components/responses/SignupSessionNotFoundError"
