openapi: 3.1.0
info:
  title: FinTech Information Forum API
  version: 1.0.0
  description: API document for FinTech Information Forum.
servers:
  - url: https://fif.com/api/v1
    description: FIF API
