openapi: 3.1.0
tags:
  - name: auth
    description: Endpoints dealing with authentication and authorization

paths:
  /auth/login/validate:
    post:
      tags:
        - auth
      summary: Validate credentials
      description: Validates user login credentials.
      operationId: auth.login.validate
      requestBody:
        required: true
        description: Login credentials
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/components/schemas/ValidateCredentials"
      responses:
        "200":
          description: Success
        "400":
          $ref: "./errors.yaml#/components/responses/ValidateCredentialsValidationError"
