openapi: 3.1.0
tags:
  - name: signup
    description: Endpoints dealing with user signup

paths:
  /auth/signup/details:
    post:
      tags:
        - signup
      summary: Set user details (step 1/3 of signup)
      description: First step of the signup process. Validates user details.
      operationId: auth.signup.details
      requestBody:
        required: true
        description: User registration details.
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/components/schemas/SignupDetails"
      responses:
        "200":
          $ref: "./responses.yml#/responses/SuccessfulSignupStep"
        "400":
          $ref: "./errors.yaml#/components/responses/SignupDetailsValidationError"
        "409":
          $ref: "./errors.yaml#/components/responses/SignupDetailsEmailExistsError"

  /auth/signup/password:
    post:
      tags:
        - signup
      summary: Set password (step 2/3 of signup)
      description: |
        Allows a user to define a secure password as part of the registration flow. 
        Password must meet strength requirements.
      operationId: auth.signup.password
      requestBody:
        required: true
        description: Password to set.
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/components/schemas/SignupPassword"
      responses:
        "200":
          $ref: "./responses.yml#/responses/SuccessfulSignupStep"
        "400":
          $ref: "./errors.yaml#/components/responses/SignupPasswordValidationError"
        "404":
          $ref: "./errors.yaml#/components/responses/SignupSessionNotFoundError"

  /auth/signup/finalize:
    post:
      tags:
        - signup
      summary: Finalize signup (step 3/3 of signup)
      description: |
        Final step of the signup process, creating a new user. User must accept T&C and can optionally accept marketing communications.
      operationId: auth.signup.finalize
      requestBody:
        required: true
        description: T&C acceptance and marketing consent.
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/components/schemas/SignupFinalize"
      responses:
        "201":
          $ref: "./responses.yml#/responses/SignupFinalized"
        "400":
          $ref: "./errors.yaml#/components/responses/SignupTermsValidationError"
        "404":
          $ref: "./errors.yaml#/components/responses/SignupSessionNotFoundError"
