openapi: 3.1.0
tags:
  - name: profile
    description: Endpoints dealing with user profile

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /profile:
    get:
      tags:
        - profile
      summary: Get Profile
      description: Returns user profile data
      operationId: profile.get
      security:
        - bearerAuth: []
      responses:
        "200":
          $ref: "./responses.yaml#/responses/Profile200"
        "401":
          description: "Unauthorized"

    patch:
      tags:
        - profile
      summary: Update Profile
      description: Updates user profile data. All fields are optional, only provided fields are updated. To set a field to empty, send `null`
      operationId: profile.patch
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: Profile data
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/schemas/ProfileUpdate"
      responses:
        "200":
          $ref: "./responses.yaml#/responses/Profile200"
        "400":
          $ref: "./errors.yaml#/components/responses/ProfileUpdateValidationError"
        "401":
          description: "Unauthorized"
